### ISSUE TITLE
How does the `goto-definition` and `find-references` work without rust-analyzer's support?

### ISSUE THREAD

**Issue by hsqStephenZhang** [sourcegraph/scip-rust#16]
In official [doc](https://docs.sourcegraph.com/code_navigation/references/indexers#quick-reference), the `rust-analyzer` can provide informations for `goto-definition` and `find-references`, but I've seen rust-analyzer's code and its [issue](https://github.com/rust-lang/rust-analyzer/issues/14031), the relationships field is left empty for now. 

So how does SourceGraph's code navigation works in rust? Doesn't it utilize the `relationships` field in SCIP's `SymbolInformation` type? I'm kinda confused.

**Comment by smheidrich** [comment]
I'm wondering about the same thing, did you ever find the answer to this?
